MIN_START_STOP_FRAGMENT_LENGTH = 100
START_CODONS = ['ATG']
STOP_CODONS = ['TAA', 'TAG', 'TGA']
PHYLIP_MATRIX_PRECISION = 6
SEQ_FILE_FORMAT = 'fasta'
NUCLEOTIDES = 'ATGC'
LOGGER_TIME_FORMAT = '%H:%M:%S'
